name: Build PR

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: |
          if [ -f package.json ]; then
            npm run build
          fi

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build/
