name: Manual Deployment

on:
  workflow_dispatch: # Allows manual trigger
    inputs:
      environment: # Updated to include a dropdown
        description: 'Environment to deploy (prod/uat/dev)'
        required: true
        type: choice # Specify input type as choice for dropdown
        options: # Define the dropdown options
          - uat
          - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Clean previous builds
      - name: Clean previous builds
        run: npm run clean

      # Build API
      - name: Build API
        run: npm run build

      # Verify build output
      - name: Verify build output
        run: ls -R ./dist
      # 5. Set Environment Variables for Deployment
      - name: Set Environment Variables
        run: |
          ENVIRONMENT=$(echo "${{ github.event.inputs.environment }}" | tr '[:lower:]' '[:upper:]')
          echo "APP_NAME_SECRET=AZURE_APP_NAME_${ENVIRONMENT}_BACKEND" >> $GITHUB_ENV
          echo "PUBLISH_PROFILE_SECRET=AZURE_WEBAPP_${ENVIRONMENT}_BACKEND_PUBLISH_PROFILE" >> $GITHUB_ENV

      # 6. Deploy to Azure App Service
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets[env.APP_NAME_SECRET] }}
          publish-profile: ${{ secrets[env.PUBLISH_PROFILE_SECRET] }}
          package: ./dist



