name: Manual Deployment

on:
  workflow_dispatch: # Allows manual trigger
    inputs:
      environment:
        description: 'Environment to deploy (prod/uat/dev)'
        required: true
      branch:
        description: 'Branch to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Install Dependencies
      - name: Install Dependencies
        run: npm install

      # 5. Build Application
      # - name: Build Application
      #   run: |
      #     if [ -f package.json ]; then
      #       npm run build
      #     fi

      # 5. Set Environment Variables for Deployment
      - name: Set Environment Variables
        run: |
          ENVIRONMENT=$(echo "${{ github.event.inputs.environment }}" | tr '[:lower:]' '[:upper:]')
          echo "APP_NAME_SECRET=AZURE_APP_NAME_${ENVIRONMENT}_BACKEND" >> $GITHUB_ENV
          echo "PUBLISH_PROFILE_SECRET=AZURE_WEBAPP_${ENVIRONMENT}_BACKEND_PUBLISH_PROFILE" >> $GITHUB_ENV

      # 6. Deploy to Azure App Service
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets[env.APP_NAME_SECRET] }}
          publish-profile: ${{ secrets[env.PUBLISH_PROFILE_SECRET] }}



